services:
  report-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - LOG_LEVEL=debug
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/healthz"]
      interval: 5s
      timeout: 2s
      retries: 5

  test-runner:
    image: curlimages/curl:latest
    depends_on:
      report-service:
        condition: service_healthy
    volumes:
      - ./scripts/e2e.sh:/e2e.sh
    entrypoint: ["/bin/sh", "-c", "/e2e.sh"]