name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build-test:
    name: Build, Lint, Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.23"

      - name: Install dependencies
        run: |
          go install github.com/vektra/mockery/v2@v2.51.1
          go install github.com/bufbuild/buf/cmd/buf@latest

      - name: Generate protobufs
        run: buf generate --clean --include-imports

      - name: Generate mocks
        run: mockery --config mockery.yaml

      - name: Run linters
        run: go vet ./...

      - name: Run tests
        run: go test ./... -v
